matrix:
  include:
  - os: linux
    language: scala
  - os: osx
    language: java
  - os: windows
    language: shell

jdk:
- openjdk10

sudo: false
before_install:
- if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install zulu10 sbt; fi
- if [ "$TRAVIS_OS_NAME" != "windows" ]; then curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x; fi
script:
   - sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck ^test ^scripted
   - cd examples
   - for d in */ ; do cd "$d" &&  sbt test && cd ../ ; done
