matrix:
  include:
  - os: linux
    language: scala
  - os: osx
    language: java

jdk:
- openjdk11

sudo: false
before_install:
- ./travis_setup.sh
script:
   - set -e
   - sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck ^test ^scripted
   - cd examples
   - for d in */ ; do cd "$d" &&  sbt test && cd ../ ; done
