os:
- linux
- osx
jdk:
- openjdk10
language: scala
sudo: false
before_install:
- sudo apt-get update
- curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
script:
   - sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck ^test ^scripted
   - cd examples
   - for d in */ ; do cd "$d" &&  sbt test && cd ../ ; done
